# Generated by Django 2.2.16 on 2021-03-07 14:40

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, help_text='Enter the language', max_length=20, null=True, verbose_name=catalog.models.Language),
        ),
    ]
